title: Ifra Batool
description:  6th semester Computer Science student at FAST Nuces with expertise in algorithm design, data
 structures, and software and mobile app development. Proficient in Python, Java, and C++,
 committed to collaborative problem-solving and staying current with emerging technologies.
theme: jekyll-theme-minimal
